# Generated by Django 5.1.4 on 2025-01-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
    ]
